---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: weblogic-sample-domain1
  namespace: sample-domain1-ns
spec:
  interval: 5m0s
  path: ./weblogic
  prune: true
  sourceRef:
    kind: GitRepository
    name: weblogic-manifests
  validation: client
  decryption:
    provider: sops