apiVersion: v1
kind: Secret
metadata:
  labels:
    weblogic.domainUID: "sample-domain1"
  name: sample-domain1-runtime-encryption-secret
  namespace: sample-domain1-ns
data:
  password: welcome1
type: Opaque